<?php

namespace Drupal\rssfeed\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

/**
 * Defines a form that configures form module settings
 */

class rssfeedConfigurationForm extends ConfigFormBase {

    /**
     * config settings
     * @var string
     */
    const RSS_SETTINGS = 'rssfeed.settings';

    /**
     * {@inheritdoc}
     */
    protected function getEditableConfigNames()
    {
        return [
            static::RSS_SETTINGS,
        ];
    }
    /**
     * {@inheritdoc}
     */
    public function getFormId()
    {
       return 'rssconfig_settings_form';
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(array $form, FormStateInterface $form_state)
    {
        $config = $this->config(static::RSS_SETTINGS);
        $form['rssurl'] = array(
           '#title' => $this->t('Feed URL'),
           '#description' => $this->t('Enter RSS feed url'),
           '#required' => true,
           '#type' => 'textfield',
        );
        return parent::buildForm($form, $form_state); // TODO: Change the autogenerated stub
    }
   public function submitForm(array &$form, FormStateInterface $form_state)
   {
    $this->config(static::RSS_SETTINGS)
           ->set('rssurl', $form_state->getValue('rssurl'))
           ->save();
     parent::submitForm($form, $form_state);
   }
}